{
 "title": "FIAP X - Overview",
 "tags": [ "fiapx" ],
 "panels": [
  {
   "title": "Auth Requests Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "auth_requests_total", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  },
  {
   "title": "Video Uploads Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "video_uploads_total", "legendFormat": "uploads" }
   ]
  },
  {
   "title": "Upload Duration (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(video_upload_duration_seconds_sum[5m]) / rate(video_upload_duration_seconds_count[5m])",
     "legendFormat": "avg duration"
    }
   ]
  }
 ]
}