apiVersion: v1
kind: ConfigMap
metadata:
  name: fiapx-config
  namespace: fiapx
data:
  REDIS_URL_AUTH: "redis://redis:6379/0"
  REDIS_URL_VIDEOS: "redis://redis:6379/1"
  REDIS_URL_PROCESSING: "redis://redis:6379/2"
  REDIS_URL_NOTIFICATIONS: "redis://redis:6379/3"
  MINIO_ENDPOINT: "minio:9000"
  MINIO_BUCKET: "videos"
  AUTH_SERVICE_URL: "http://auth-service:8001"
  VIDEO_UPLOAD_SERVICE_URL: "http://video-upload-service:8002"
  MAX_CONCURRENT_WORKERS: "3"
  PROCESSING_SIMULATE_TIME: "10"
  SMTP_HOST: "mailhog"
  SMTP_PORT: "1025"
