apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: fiapx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: fiapx/notification-service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_URL
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: RABBITMQ_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: AUTH_SERVICE_URL
            - name: REDIS_URL
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: REDIS_URL_NOTIFICATIONS
            - name: SMTP_HOST
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: fiapx-config
                  key: SMTP_PORT
